# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qroma-comm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import file_system_commands_pb2 as file__system__commands__pb2
import qroma_core_pb2 as qroma__core__pb2
import qroma_streams_pb2 as qroma__streams__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='qroma-comm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10qroma-comm.proto\x1a\x1a\x66ile-system-commands.proto\x1a\x10qroma-core.proto\x1a\x13qroma-streams.proto\"\xb9\x01\n\x10QromaCommCommand\x12\x19\n\x0f\x61ppCommandBytes\x18\x01 \x01(\x0cH\x00\x12(\n\x0b\x63oreCommand\x18\x02 \x01(\x0b\x32\x11.QromaCoreCommandH\x00\x12\'\n\tfsCommand\x18\x03 \x01(\x0b\x32\x12.FileSystemCommandH\x00\x12,\n\rstreamCommand\x18\x04 \x01(\x0b\x32\x13.QromaStreamCommandH\x00\x42\t\n\x07\x63ommand\"\xc2\x01\n\x11QromaCommResponse\x12\x1a\n\x10\x61ppResponseBytes\x18\x01 \x01(\x0cH\x00\x12*\n\x0c\x63oreResponse\x18\x02 \x01(\x0b\x32\x12.QromaCoreResponseH\x00\x12)\n\nfsResponse\x18\x03 \x01(\x0b\x32\x13.FileSystemResponseH\x00\x12.\n\x0estreamResponse\x18\x05 \x01(\x0b\x32\x14.QromaStreamResponseH\x00\x42\n\n\x08responseb\x06proto3'
  ,
  dependencies=[file__system__commands__pb2.DESCRIPTOR,qroma__core__pb2.DESCRIPTOR,qroma__streams__pb2.DESCRIPTOR,])




_QROMACOMMCOMMAND = _descriptor.Descriptor(
  name='QromaCommCommand',
  full_name='QromaCommCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appCommandBytes', full_name='QromaCommCommand.appCommandBytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coreCommand', full_name='QromaCommCommand.coreCommand', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fsCommand', full_name='QromaCommCommand.fsCommand', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='streamCommand', full_name='QromaCommCommand.streamCommand', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='QromaCommCommand.command',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=88,
  serialized_end=273,
)


_QROMACOMMRESPONSE = _descriptor.Descriptor(
  name='QromaCommResponse',
  full_name='QromaCommResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appResponseBytes', full_name='QromaCommResponse.appResponseBytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coreResponse', full_name='QromaCommResponse.coreResponse', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fsResponse', full_name='QromaCommResponse.fsResponse', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='streamResponse', full_name='QromaCommResponse.streamResponse', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='QromaCommResponse.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=276,
  serialized_end=470,
)

_QROMACOMMCOMMAND.fields_by_name['coreCommand'].message_type = qroma__core__pb2._QROMACORECOMMAND
_QROMACOMMCOMMAND.fields_by_name['fsCommand'].message_type = file__system__commands__pb2._FILESYSTEMCOMMAND
_QROMACOMMCOMMAND.fields_by_name['streamCommand'].message_type = qroma__streams__pb2._QROMASTREAMCOMMAND
_QROMACOMMCOMMAND.oneofs_by_name['command'].fields.append(
  _QROMACOMMCOMMAND.fields_by_name['appCommandBytes'])
_QROMACOMMCOMMAND.fields_by_name['appCommandBytes'].containing_oneof = _QROMACOMMCOMMAND.oneofs_by_name['command']
_QROMACOMMCOMMAND.oneofs_by_name['command'].fields.append(
  _QROMACOMMCOMMAND.fields_by_name['coreCommand'])
_QROMACOMMCOMMAND.fields_by_name['coreCommand'].containing_oneof = _QROMACOMMCOMMAND.oneofs_by_name['command']
_QROMACOMMCOMMAND.oneofs_by_name['command'].fields.append(
  _QROMACOMMCOMMAND.fields_by_name['fsCommand'])
_QROMACOMMCOMMAND.fields_by_name['fsCommand'].containing_oneof = _QROMACOMMCOMMAND.oneofs_by_name['command']
_QROMACOMMCOMMAND.oneofs_by_name['command'].fields.append(
  _QROMACOMMCOMMAND.fields_by_name['streamCommand'])
_QROMACOMMCOMMAND.fields_by_name['streamCommand'].containing_oneof = _QROMACOMMCOMMAND.oneofs_by_name['command']
_QROMACOMMRESPONSE.fields_by_name['coreResponse'].message_type = qroma__core__pb2._QROMACORERESPONSE
_QROMACOMMRESPONSE.fields_by_name['fsResponse'].message_type = file__system__commands__pb2._FILESYSTEMRESPONSE
_QROMACOMMRESPONSE.fields_by_name['streamResponse'].message_type = qroma__streams__pb2._QROMASTREAMRESPONSE
_QROMACOMMRESPONSE.oneofs_by_name['response'].fields.append(
  _QROMACOMMRESPONSE.fields_by_name['appResponseBytes'])
_QROMACOMMRESPONSE.fields_by_name['appResponseBytes'].containing_oneof = _QROMACOMMRESPONSE.oneofs_by_name['response']
_QROMACOMMRESPONSE.oneofs_by_name['response'].fields.append(
  _QROMACOMMRESPONSE.fields_by_name['coreResponse'])
_QROMACOMMRESPONSE.fields_by_name['coreResponse'].containing_oneof = _QROMACOMMRESPONSE.oneofs_by_name['response']
_QROMACOMMRESPONSE.oneofs_by_name['response'].fields.append(
  _QROMACOMMRESPONSE.fields_by_name['fsResponse'])
_QROMACOMMRESPONSE.fields_by_name['fsResponse'].containing_oneof = _QROMACOMMRESPONSE.oneofs_by_name['response']
_QROMACOMMRESPONSE.oneofs_by_name['response'].fields.append(
  _QROMACOMMRESPONSE.fields_by_name['streamResponse'])
_QROMACOMMRESPONSE.fields_by_name['streamResponse'].containing_oneof = _QROMACOMMRESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['QromaCommCommand'] = _QROMACOMMCOMMAND
DESCRIPTOR.message_types_by_name['QromaCommResponse'] = _QROMACOMMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QromaCommCommand = _reflection.GeneratedProtocolMessageType('QromaCommCommand', (_message.Message,), {
  'DESCRIPTOR' : _QROMACOMMCOMMAND,
  '__module__' : 'qroma_comm_pb2'
  # @@protoc_insertion_point(class_scope:QromaCommCommand)
  })
_sym_db.RegisterMessage(QromaCommCommand)

QromaCommResponse = _reflection.GeneratedProtocolMessageType('QromaCommResponse', (_message.Message,), {
  'DESCRIPTOR' : _QROMACOMMRESPONSE,
  '__module__' : 'qroma_comm_pb2'
  # @@protoc_insertion_point(class_scope:QromaCommResponse)
  })
_sym_db.RegisterMessage(QromaCommResponse)


# @@protoc_insertion_point(module_scope)
