# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qroma-config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import qroma_types_pb2 as qroma__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='qroma-config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12qroma-config.proto\x1a\x11qroma-types.proto\"W\n\x17QromaCommSerialIoConfig\x12\x10\n\x08\x62\x61udRate\x18\x01 \x01(\r\x12\x14\n\x0crxBufferSize\x18\x02 \x01(\r\x12\x14\n\x0ctxBufferSize\x18\x03 \x01(\r\"\\\n\x18QromaCommReportingConfig\x12!\n\x08logLevel\x18\x01 \x01(\x0e\x32\x0f.Qroma_LogLevel\x12\x1d\n\x15heartbeatIntervalInMs\x18\x02 \x01(\r\"w\n\x0fQromaCommConfig\x12\x30\n\x0eserialIoConfig\x18\x01 \x01(\x0b\x32\x18.QromaCommSerialIoConfig\x12\x32\n\x0freportingConfig\x18\x02 \x01(\x0b\x32\x19.QromaCommReportingConfigb\x06proto3'
  ,
  dependencies=[qroma__types__pb2.DESCRIPTOR,])




_QROMACOMMSERIALIOCONFIG = _descriptor.Descriptor(
  name='QromaCommSerialIoConfig',
  full_name='QromaCommSerialIoConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='baudRate', full_name='QromaCommSerialIoConfig.baudRate', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rxBufferSize', full_name='QromaCommSerialIoConfig.rxBufferSize', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='txBufferSize', full_name='QromaCommSerialIoConfig.txBufferSize', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=128,
)


_QROMACOMMREPORTINGCONFIG = _descriptor.Descriptor(
  name='QromaCommReportingConfig',
  full_name='QromaCommReportingConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='logLevel', full_name='QromaCommReportingConfig.logLevel', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heartbeatIntervalInMs', full_name='QromaCommReportingConfig.heartbeatIntervalInMs', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=222,
)


_QROMACOMMCONFIG = _descriptor.Descriptor(
  name='QromaCommConfig',
  full_name='QromaCommConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serialIoConfig', full_name='QromaCommConfig.serialIoConfig', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reportingConfig', full_name='QromaCommConfig.reportingConfig', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=343,
)

_QROMACOMMREPORTINGCONFIG.fields_by_name['logLevel'].enum_type = qroma__types__pb2._QROMA_LOGLEVEL
_QROMACOMMCONFIG.fields_by_name['serialIoConfig'].message_type = _QROMACOMMSERIALIOCONFIG
_QROMACOMMCONFIG.fields_by_name['reportingConfig'].message_type = _QROMACOMMREPORTINGCONFIG
DESCRIPTOR.message_types_by_name['QromaCommSerialIoConfig'] = _QROMACOMMSERIALIOCONFIG
DESCRIPTOR.message_types_by_name['QromaCommReportingConfig'] = _QROMACOMMREPORTINGCONFIG
DESCRIPTOR.message_types_by_name['QromaCommConfig'] = _QROMACOMMCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QromaCommSerialIoConfig = _reflection.GeneratedProtocolMessageType('QromaCommSerialIoConfig', (_message.Message,), {
  'DESCRIPTOR' : _QROMACOMMSERIALIOCONFIG,
  '__module__' : 'qroma_config_pb2'
  # @@protoc_insertion_point(class_scope:QromaCommSerialIoConfig)
  })
_sym_db.RegisterMessage(QromaCommSerialIoConfig)

QromaCommReportingConfig = _reflection.GeneratedProtocolMessageType('QromaCommReportingConfig', (_message.Message,), {
  'DESCRIPTOR' : _QROMACOMMREPORTINGCONFIG,
  '__module__' : 'qroma_config_pb2'
  # @@protoc_insertion_point(class_scope:QromaCommReportingConfig)
  })
_sym_db.RegisterMessage(QromaCommReportingConfig)

QromaCommConfig = _reflection.GeneratedProtocolMessageType('QromaCommConfig', (_message.Message,), {
  'DESCRIPTOR' : _QROMACOMMCONFIG,
  '__module__' : 'qroma_config_pb2'
  # @@protoc_insertion_point(class_scope:QromaCommConfig)
  })
_sym_db.RegisterMessage(QromaCommConfig)


# @@protoc_insertion_point(module_scope)
