# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qroma-types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11qroma-types.proto\"1\n\x10Qroma_LogMessage\x12\x0c\n\x04tick\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t*`\n\x0eQroma_LogLevel\x12\x10\n\x0cLogLevel_All\x10\x00\x12\x11\n\rLogLevel_Info\x10\n\x12\x12\n\x0eLogLevel_Error\x10\x64\x12\x15\n\x10LogLevel_Nothing\x10\xff\x01*\xac\x01\n\x13Qroma_DebugCommMode\x12\x18\n\x14\x44\x65\x62ugCommMode_NotSet\x10\x00\x12\x16\n\x12\x44\x65\x62ugCommMode_None\x10\x01\x12\x1c\n\x18\x44\x65\x62ugCommMode_SerialOnly\x10\x02\x12\x1f\n\x1b\x44\x65\x62ugCommMode_BluetoothOnly\x10\x03\x12$\n DebugCommMode_SerialAndBluetooth\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qroma_types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QROMA_LOGLEVEL']._serialized_start=72
  _globals['_QROMA_LOGLEVEL']._serialized_end=168
  _globals['_QROMA_DEBUGCOMMMODE']._serialized_start=171
  _globals['_QROMA_DEBUGCOMMMODE']._serialized_end=343
  _globals['_QROMA_LOGMESSAGE']._serialized_start=21
  _globals['_QROMA_LOGMESSAGE']._serialized_end=70
# @@protoc_insertion_point(module_scope)
