# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qroma-config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import qroma_types_pb2 as qroma__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12qroma-config.proto\x1a\x11qroma-types.proto\"W\n\x17QromaCommSerialIoConfig\x12\x10\n\x08\x62\x61udRate\x18\x01 \x01(\r\x12\x14\n\x0crxBufferSize\x18\x02 \x01(\r\x12\x14\n\x0ctxBufferSize\x18\x03 \x01(\r\"\\\n\x18QromaCommReportingConfig\x12!\n\x08logLevel\x18\x01 \x01(\x0e\x32\x0f.Qroma_LogLevel\x12\x1d\n\x15heartbeatIntervalInMs\x18\x02 \x01(\r\"w\n\x0fQromaCommConfig\x12\x30\n\x0eserialIoConfig\x18\x01 \x01(\x0b\x32\x18.QromaCommSerialIoConfig\x12\x32\n\x0freportingConfig\x18\x02 \x01(\x0b\x32\x19.QromaCommReportingConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qroma_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QROMACOMMSERIALIOCONFIG']._serialized_start=41
  _globals['_QROMACOMMSERIALIOCONFIG']._serialized_end=128
  _globals['_QROMACOMMREPORTINGCONFIG']._serialized_start=130
  _globals['_QROMACOMMREPORTINGCONFIG']._serialized_end=222
  _globals['_QROMACOMMCONFIG']._serialized_start=224
  _globals['_QROMACOMMCONFIG']._serialized_end=343
# @@protoc_insertion_point(module_scope)
