# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qroma-comm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import file_system_commands_pb2 as file__system__commands__pb2
from . import qroma_comm_config_commands_pb2 as qroma__comm__config__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10qroma-comm.proto\x1a\x1a\x66ile-system-commands.proto\x1a qroma-comm-config-commands.proto\"\x97\x01\n\x10QromaCommCommand\x12\x19\n\x0f\x61ppCommandBytes\x18\x01 \x01(\x0cH\x00\x12\'\n\tfsCommand\x18\x02 \x01(\x0b\x32\x12.FileSystemCommandH\x00\x12\x34\n\x11\x63ommConfigCommand\x18\x03 \x01(\x0b\x32\x17.QromaCommConfigCommandH\x00\x42\t\n\x07\x63ommand\"H\n\x1aQromaCommHeartbeatResponse\x12\x12\n\nuptimeInMs\x18\x01 \x01(\r\x12\x16\n\x0eheartbeatTicks\x18\x02 \x01(\r\"\xd8\x01\n\x11QromaCommResponse\x12\x1a\n\x10\x61ppResponseBytes\x18\x01 \x01(\x0cH\x00\x12)\n\nfsResponse\x18\x02 \x01(\x0b\x32\x13.FileSystemResponseH\x00\x12\x36\n\x12\x63ommConfigResponse\x18\x03 \x01(\x0b\x32\x18.QromaCommConfigResponseH\x00\x12\x38\n\x11heartbeatResponse\x18\x04 \x01(\x0b\x32\x1b.QromaCommHeartbeatResponseH\x00\x42\n\n\x08responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qroma_comm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QROMACOMMCOMMAND']._serialized_start=83
  _globals['_QROMACOMMCOMMAND']._serialized_end=234
  _globals['_QROMACOMMHEARTBEATRESPONSE']._serialized_start=236
  _globals['_QROMACOMMHEARTBEATRESPONSE']._serialized_end=308
  _globals['_QROMACOMMRESPONSE']._serialized_start=311
  _globals['_QROMACOMMRESPONSE']._serialized_end=527
# @@protoc_insertion_point(module_scope)
